### ISSUE TITLE
ConvNet are alowed for the 89's Fridays

### ISSUE THREAD

**Issue by agrignard** [RELNO/89Fridays#10]
We should help Yan LeCun with its slides

<img width="1920" alt="screen shot 2018-02-22 at 23 51 16" src="https://user-images.githubusercontent.com/3928502/36578489-871cb70e-182b-11e8-94f5-a78f7289d7e1.png">

**Comment by RELNO** [comment]
Too late, we're already deeeeeeeeeeep.
