### ISSUE TITLE
List of Real world issues

### ISSUE THREAD

**Issue by LAAP** [RELNO/89Fridays#5]
Hi 89ers... Since CS never made a 99Friday party, this 79er has a first real-world question for you:

-What is the inner process of making a 99FP - 89FP?

**Comment by RELNO** [comment]
@LAAP Could you start a conversation with Jifei Ou? He looks like the go to person.

**Comment by LAAP** [comment]
Hi @RELNO,
I have approached him yesterday at the 99FP, and he said that he can explain everything to us... there is a special fund for alcohol, where we have to apply. I will reach him out using the latest technology of communication; a packet switching network by implementing the protocol suite TCP/IP through ARPANET   ;)

**Comment by LAAP** [comment]
Wait for a minute! We are at the end of the 80's no in the 70's! I can use a crazier network, I can use the first non-profit research and education network PSINet!
